### ISSUE TITLE
Cannot read properties of undefined

### ISSUE THREAD

**Issue by CecoSvidovski** [yuichiroaoki/poly-flashloan-bot#13]
The script runs normally for some time and then it crashes showing this:

```
TypeError: Cannot read properties of undefined (reading 'status')
    at E:\poly-flashloan-bot-main\dist\inchPrice.js:81:33
    at Generator.next (<anonymous>)
    at fulfilled (E:\poly-flashloan-bot-main\dist\inchPrice.js:5:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by CecoSvidovski** [comment]
Fixed it and made a pull request

> The script runs normally for some time and then it crashes showing this:
> 
> ```
> TypeError: Cannot read properties of undefined (reading 'status')
>     at E:\poly-flashloan-bot-main\dist\inchPrice.js:81:33
>     at Generator.next (<anonymous>)
>     at fulfilled (E:\poly-flashloan-bot-main\dist\inchPrice.js:5:58)
>     at runMicrotasks (<anonymous>)
>     at processTicksAndRejections (node:internal/process/task_queues:96:5)
> ```

**Comment by yuichiroaoki** [comment]
> Fixed it and made a pull request
> 
> > The script runs normally for some time and then it crashes showing this:
> > ```
> > TypeError: Cannot read properties of undefined (reading 'status')
> >     at E:\poly-flashloan-bot-main\dist\inchPrice.js:81:33
> >     at Generator.next (<anonymous>)
> >     at fulfilled (E:\poly-flashloan-bot-main\dist\inchPrice.js:5:58)
> >     at runMicrotasks (<anonymous>)
> >     at processTicksAndRejections (node:internal/process/task_queues:96:5)
> > ```

Thank you for fixing the bug. Merged this pull request.
