### ISSUE TITLE
Fail with error 'UniswapV2Library: INSUFFICIENT_INPUT_AMOUNT' how can i resolve this error

### ISSUE THREAD

**Issue by gsngsn123** [yuichiroaoki/poly-flashloan-bot#16]
Fail with error 'UniswapV2Library: INSUFFICIENT_INPUT_AMOUNT'
how can i resolve this error

**Comment by yuichiroaoki** [comment]
Maybe the bot couldn't borrow tokens because of the wrong pool address or the lack of pool tokens.  I'm going to check and update the pool addresses.

**Comment by gsngsn123** [comment]
please update when it finish
