### ISSUE TITLE
Request failed with status code 400

### ISSUE THREAD

**Issue by trancee** [yuichiroaoki/poly-flashloan-bot#2]
Thank you for sharing your code!

I have it up and running by following your instructions but I keep getting lots of errors like `Request failed with status code 400`. What am I doing wrong? 

I am on the Polygon mainnet and the smart contract is deployed.

Thanks for your help.

**Comment by yuichiroaoki** [comment]
Sorry that the error message is confusing.

The error message you got means probably the bot successfully sent a request to 1inch API, but 1inch failed to respond price data.


![image](https://user-images.githubusercontent.com/45054071/144749151-2aa85d07-0a0f-4411-91ab-36d5d50c0538.png)

https://github.com/yuichiroaoki/poly-flashloan-bot/commit/8617ebf9a73fde49fdfbfb215f18a31264462bf3

ref.
https://github.com/yuichiroaoki/poly-flash/issues/1#issuecomment-985954247
