### ISSUE TITLE
Request failed with status code 400

### ISSUE THREAD

**Issue by GNMarques** [yuichiroaoki/poly-flashloan-bot#4]
Hi,

Sorry to bother you again with the same issue.
I deployed in the mainnet and I still get the same error message.
I can see in alchemy I am sucefully making API calls but I still get the same error message.
Do you  know how to solve this.

Thanks in advance.

**Comment by yuichiroaoki** [comment]
Hi.
Did you update your code?? That error comes from the bot code.
You can try running the following commands:

```bash
git pull origin main
yarn install 
yarn build
yarn start
```

**Comment by GNMarques** [comment]
Thank you very much for yor help.
I will try

**Comment by GNMarques** [comment]
now I m getting "Error: Failed to fetch data from 1inch" do you have any ideas of the source of this problem?

**Comment by yuichiroaoki** [comment]
That is expected behavior and meaning the bot is working correctly. 
When the bot execute the flashloan and there's not an arbitrage opportunity, the transaction will be reverted with that message. 

https://github.com/yuichiroaoki/poly-flash/blob/c2b8e78c0d7c57005715362ba17ba76639feba3e/contracts/Flashloan.sol#L131

**Comment by GNMarques** [comment]
Nice thanks. I will wait for a while I let you know when I find a deal.
Did you try it?
I checked on polygonscan your contract (0x0e0ec2c716b5ba2512af9d3790d8804da42ddd58) have some transactions reverted did you solve that issue?

**Comment by hkno1** [comment]
I think there's an issue with the 1inch quote API? Keeps returning an error with status code 400

**Comment by leuhk** [comment]
I think there's an issue with the 1inch quote API? Keeps returning an error with status code 400

**Comment by yuichiroaoki** [comment]
> Nice thanks. I will wait for a while I let you know when I find a deal. Did you try it? I checked on polygonscan your contract (0x0e0ec2c716b5ba2512af9d3790d8804da42ddd58) have some transactions reverted did you solve that issue?

Some people modified the code and run flashloan with that contract, so I'm not sure why.


However, the following error message is expected when you run flashloan with no arbitrage opportunities.
```Fail with error 'Not enough amount to return loan'```

![image](https://user-images.githubusercontent.com/45054071/146189018-cc14369b-4f0f-49f5-b68e-bb9797d721fa.png)
