### ISSUE TITLE
Fail with error 'SafeERC20: low-level call failed'

### ISSUE THREAD

**Issue by trancee** [yuichiroaoki/poly-flashloan-bot#5]
I made some changes to the code (but not the smart contract) and once it found an arbitrage opportunity and it called the smart contract, it failed with the above error message.

Is there something wrong in the contract, or did I do something wrong on my side?

Any help would be much appreciated.

https://polygonscan.com/tx/0xa2685e50e596df610877ddf1f871b5443e232133f02a51310552f5c6d9e5b588

**Comment by yuichiroaoki** [comment]
Not sure.  Some lending pools of dodo seem to be not working, so ..

Well it's hard to debug. .

**Comment by trancee** [comment]
I am a bit confused since it seems to be hardcoded what dodo pool to use:
https://github.com/yuichiroaoki/poly-flashloan-bot/blob/5e1cad274f9e94c36bef3e4c9b962292c15ecb5f/src/flashloan.ts#L33

Or am I wrong?

**Comment by yuichiroaoki** [comment]
Yeah that's something needs to be changed. I haven't tested the code with other dodo pools.
