### ISSUE TITLE
Discord and telegram group

### ISSUE THREAD

**Issue by yuichiroaoki** [yuichiroaoki/poly-flashloan-bot#92]

**Comment by Solh4ckm1n** [comment]
let's go ;)

**Comment by BOBseal** [comment]
yesss let's go

**Comment by pamarthisai** [comment]
yes its better

**Comment by VirtualConnectGroup** [comment]
What is the Discord Server addr?

**Comment by james2402** [comment]
great idea

**Comment by yuichiroaoki** [comment]
## Discord link

https://discord.gg/Ytnyug4N

**Comment by yuichiroaoki** [comment]
## Telegram

https://t.me/+-jFCzSN5ADQ2MTVl

**Comment by sirEven** [comment]
could you provide a new invite link for discord please?

**Comment by yuichiroaoki** [comment]
There you go

https://discord.gg/WpEMfYmJ

**Comment by growupinv** [comment]
> https://t.me/+-jFCzSN5ADQ2MTVl

hi, outdated link, can u update pls

**Comment by blackjj3110** [comment]
> ## Telegram
> https://t.me/+-jFCzSN5ADQ2MTVl

HI Yuichiro san, would you please update TG link as well, thanks~

**Comment by yuichiroaoki** [comment]
Okay 

https://t.me/+C8jMa2BbEjs4ODBl

**Comment by bensonnjonjo** [comment]
@yuichiroaoki please provide a new invite link for discord, the last one expired

**Comment by yuichiroaoki** [comment]
Here 
https://discord.gg/HCsK94TB

**Comment by Kru0489** [comment]
@yuichiroaoki  can you please post the links again? they've expired.

**Comment by tdev00** [comment]
@yuichiroaoki can you please send me a link to your discord and/or telegram?
