### ISSUE TITLE
Analysis - % Diff inter Exchanges, Fee Uniswap, Fee Flash Loan - Very Difficult Opportunities

### ISSUE THREAD

**Issue by JulioSarda** [yuichiroaoki/poly-flashloan-bot#96]
Hi Yuchi !! Hello, with the fee of Uniswap (0.05) for transaction, I have to found an opportunity of arb of 0.15 %  minimum for some profit. (P = 0.15 - (0.05 x 2) ).
If use Flash Loan i need add 0.09 more (0.24 Total for same profit).
I run the Bot for 24 hs for monitoring prices, and the best oportunities  are the 0.1 % max.
Very far to 0.15 and 0.24 necessary.
Other Defi with minors Fee ?
Or I have some wrong in my analize. 🙃

**Comment by JulioSarda** [comment]
Any idea ?

**Comment by yuichiroaoki** [comment]
I think swap fees are already included in the token amount estimate. So, you only have to think about a transaction fee if you're using dodo flashloan.

**Comment by JulioSarda** [comment]
Thanks
