### ISSUE TITLE
Testing - Error encountered during contract execution [execution reverted] 

### ISSUE THREAD

**Issue by JulioSarda** [yuichiroaoki/poly-flashloan-bot#97]
Hello !!
I was running tests.

Method:	0x0cdabeba

Contract: 0x33d8d437796bd43bdccc6740c585f4a15d1070b7 

Error: Warning! Error encountered during contract execution [execution reverted] 

Status: Fail

I do not know if the error produced is because the loan is reversed because it cannot be paid due to no profit
or 
because of a failure in one of the Swaps.

How to know?

I see that in other people's tests it gives the same error.

Thank you

**Comment by JulioSarda** [comment]
I removed almost all the code from the contract and it still gives the same error.

Error: Warning! Error encountered during contract execution [execution reverted]

In Remix say "Internal JSON-RPC error".

any ideas ?

Thanks.

**Comment by saedmohamad** [comment]
im encountering the same issue, any ideas?

**Comment by saedmohamad** [comment]
Hey julio any chance you could help me out here 🙏
